language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "4"
    - "5"
matrix:
    fast_finish: true
    allow_failures:
        - node_js: "5"
env:
    global:
        - NODE_ENV=test
services:
    - couchdb

before_install:
    # make sudoer use same PATH than default user (includes npm & node)
    - npm install -g npm@latest-2
    - npm install -g coffee-script
    - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

script:
    # Don't use npm run test, it adds a lot of npm_config_ env variables
    - sudo cake --use-js tests

after_failure:
    - env | grep PATH
    - sudo env | grep PATH
